### ISSUE TITLE
System.DllNotFoundException: "openal32.dll"

### ISSUE THREAD

**Issue by TheBlubb14** [NoobDevGame/GameJam2017#2]
![](http://puu.sh/tfzBz/ec6593e958.png)

**Comment by susch19** [comment]
Keine Zeit :( habe Meeting aufm Herd

**Comment by fnawratil** [comment]
Diese Abteilung ist nicht zuständig!

**Comment by susch19** [comment]
LINUX: Geh in die Packages von Nuget und dann sollte dort eine OpenTK Config File im Lib Folder sein, also beim Engineous package. Diese muss in den Output Folder
WINDOWS: Installieren...OpenAl installieren
